= VMware vCenter Server Appliance (VCSA) Deployment Steps
These deployment step will walk through the deployment of a VMware vCenter Server Appliance onto a single VMware ESXi hypervisor. 

== Prerequisites 
* There is an ESXi hypervisor already deployed with networking configured

* Installation media for the VCSA has been https://customerconnect.vmware.com/en/downloads/info/slug/datacenter_cloud_infrastructure/vmware_vsphere/7_0[Downloaded]

* DNS is configured and functioning correctly within the environment with A records  created for both the ESXi hypervisor and the VCSA being deployed.

* NTP is configured and functioning correctly within the environment

NOTE: There are workarounds if DNS and/ or NTP are not yet configured within the environment

* Information in the following tables must be gathered as prerequisite to deploying the VMware VCSA as it will be required to populate the deployment template file.

.ESXi Data
[options="header"]
|===
|ESX Property | Value

|ESX_SERVER
|IP Address or hostname

|ESX_USER_NAME
|root

|ESX_USER_PASS 
|<hidden>

|ESX_DATASTORE
|datastore1

|ESX_NETWORK
| VM Network

|===

.VCSA Data
[options="header"]
|===
|Virtual Environment Property | Value

|VCSA_SERVER
|Hostname

|VCSA_IP_ADDRESS
|IP Address

|VCSA_IP_GATEWAY
|IP Address

|VCSA_IP_DNS
|IP Address

|VCSA_NTP
|IP Address

|VCSA_USER_NAME
|administrator@vsphere.local

|VCSA_USER_PASS
|<hidden>

|VCSA_SSO_PASS
|<hidden>

|===

== Deployment Steps
IMPORTANT: These deployment steps were drafted while deploying using RHEL 8.6. 

. If not already deployed, deploy a RHEL system running RHEL 8.6 as the "deployment VM". 

NOTE: Newer and older versions should work however they will require different versions of the dependency package. 

[start=2]
. Install libnsl package within the deployment VM
.. If satelite is online, run the following command:
[example]
`sudo dnf install libnsl`
.. If satellite is not online:
... The package will need to be https://access.redhat.com/downloads/content/package-browser[downloaded] and airgapped to the system.
... The version of libnsl needs to match the version of glibc. Run the following command to check:
[example]
`rpm -qa | grep glibc`
... Once the package is on the deployment VM run the following command to install
[example]
`sudo rpm -i <rpm_package>`

. Create a directory to mount the VCSA installation media
[example]
`mkdir /vcsa-deployment`

. Mount the VCSA installation media to the deployment VM
[example]
`mount /dev/sr0 /vcsa-deployment`

. Locate, copy, and rename the template file embedded_vCSA_on_ESXi.json to vctemplate.json
[example]
`cp /vcsa-deployment/vcsa-cli-installer/template/install/embedded_vCSA_on_ESXi.json /tmp/vctemplate.json`

. Make modifications to the vctemplate.json file to reflect the environment.

====
[source,json]
----
{
    "__version": "2.13.0",
    "__comments": "Sample template to deploy a vCenter Server Appliance with an embedded Platform Services Controller on an ESXi host.",
    "new_vcsa": {
        "esxi": {
            "hostname": "<FQDN or IP address of the ESXi host on which to deploy the new appliance>", // <1>
            "username": "root", // <2>
            "password": "<Password of the ESXi host root user>", // <3>
            "deployment_network": "VM Network", // <4>
            "datastore": "<ESXi host datastore>" // <5>
        },
        "appliance": {
            "__comments": [
                "You must provide the 'deployment_option' key with a value, which will affect the vCenter Server Appliance's configuration parameters, such as the vCenter Server Appliance's number of vCPUs, the memory size, the storage size, and the maximum numbers of ESXi hosts and VMs which can be managed. For a list of acceptable values, run the supported deployment sizes help, i.e. vcsa-deploy --supported-deployment-sizes"
            ],
            "thin_disk_mode": true,
            "deployment_option": "small", // <6>
            "name": "Embedded-vCenter-Server-Appliance" // <7>
        },
        "network": {
            "ip_family": "ipv4", // <8>
            "mode": "static", // <9>
            "system_name": "<FQDN or IP address for the appliance>", // <10>
            "ip": "<Static IP address>", // <11>
            "prefix": "<Network prefix length>", // <12>
            "gateway": "<Gateway IP address>", // <13>
            "dns_servers": [
                "<DNS Server IP Address>" // <14>
            ]
        },
        "os": {
            "password": "<Appliance root password>", // <15>
            "ntp_servers": "time.nist.gov", // <16>
            "ssh_enable": false // <17>
        },
        "sso": {
            "password": "<vCenter Single Sign-On administrator password>", // <18>
            "domain_name": "vsphere.local" // <19>
        }
    },
    "ceip": {
        "description": {
            "__comments": [
                "++++VMware Customer Experience Improvement Program (CEIP)++++",
                "VMware's Customer Experience Improvement Program (CEIP) ",
                "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
            ]
        },
        "settings": {
            "ceip_enabled": true // <20>
        }
    }
}
----
<1> = { ESX_SERVER }
<2> = { ESX_USER_NAME }
<3> = { ESX_USER_PASS }
<4> = { ESX_NETWORK }
<5> = { ESX_DATASTORE }
<6> = The default size (small) supports 100 hosts and 1,000 virtual machines. If your deployment will exceed this please review VMware documentation and adjust accordingly.
<7> = { VCSA_SERVER } // this is the name of the VM as displayed in inventory not the hostname of the system as it will be resolved with DNS but they can be the same
<8> = Leave default unless IPv6 will be used. These instructions do not currenly account for IPv6.
<9> = Leave default unless DHCP will be used. These instructions do not currenly account for DHCP.
<10> = { VCSA_SERVER }
<11> = { VCSA_IP_ADDRESS }
<12> = Leave default unless the network is of a different size.
<13> = { VCSA_IP_GATEWAY }
<14> = { VCSA_IP_DNS }
<15> = { VCSA_USER_PASS }
<16> = { VCSA_NTP }
<17> = Leave default unless you will require SSH access to the VCSA. Note: SSH can be enabled after deployment if needed.
<18> = { VCSA_SSO_PASS }
<19> = Leave default unless a custom domain is desired. Note: This is not the domain name for your existing network. This is for local authentication. Your existing authentication domain can be added after deployment. See VMware documentation.
<20> = If your deployment is disconnected (not connected to the internet), this optional setting should be set to false.
====

[start=7]  
. Run the command to deploy the VCSA pointing to the vctemplate.json file

[example]
`./vcsa-deployment/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula --acknowledge-ceip --terse -no-ssl-certificate-verification ./tmp/vctemplate.json` 

The installation should not take more than 25 minutes to complete and once it is complete you can log into the VCSA, create supporting resources (datacenter, cluster, etc), add all of the ESXi hosts

